version: 2

sources:
    - name: staging
      database: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: portfolio_stg
      tables:
        - name: staging_films
        - name: staging_people
        - name: staging_planets